sudo: required
services:
  - docker

before_install:
  - docker build -t iantonenko/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e "CI=true" iantonenko/react-test npm run test

after_success:
  - docker build -t iantonenko/multi-client ./client
  - docker build -t iantonenko/multi-nginx ./nginx
  - docker build -t iantonenko/multi-server ./server
  - docker build -t iantonenko/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push iantonenko/multi-client
  - docker push iantonenko/multi-nginx
  - docker push iantonenko/multi-server
  - docker push iantonenko/multi-worker

#deploy:
#  provider: elasticbeanstalk
#  region: us-east-1
#  app: multi-docker
#  env: MultiDocker-env
#  bucket_name: elasticbeanstalk-us-east-1-853885893816
#  bucket_path: docker-multi
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key:
#    secure: $AWS_SECRET_KEY
